/**
 * Release notes — newest entry first.
 *
 * This file is the single source of truth for the app version. Each entry
 * carries an explicit two-number `version` (e.g. "1.0", "1.1", "2.0").
 * The newest entry's version is exported as APP_VERSION and shown in the
 * sidebar footer, so the footer and the latest release note never drift.
 *
 * To cut a release: add a new object at the TOP with the next version
 * number and that release's changes.
 *
 * `internalOnly: true` marks a release whose changes are all internal-only
 * features. Customers still SEE the version and its date — a hole in a numbered
 * sequence invites more curiosity than a bland line does — but read "Internal
 * improvements" and a single line instead of the changes.
 *
 * `customerSummary` (optional, only meaningful alongside internalOnly) replaces
 * that single line. Use it when a mostly-internal release does contain one thing
 * customers should know, so the choice is not between exposing everything and
 * exposing nothing.
 */
export const RELEASE_NOTES = [
  {
    version: "4.7",
    date: "2026-08-26",
    title: "Who is triggering a WEM licence",
    changes: [
      "Roles › Permissions vs. Users has a third tab, WEM License, alongside Permission Search and Hourly Interacting. It finds every user whose roles carry a permission that requires a Workforce Engagement Management add-on, names the role and the permissions responsible, and shows whether the permission came from the user directly or from a group.",
      "The verdict comes from Genesys itself. Rather than compare permissions against a list of our own, the page asks the same licence-inference the Genesys admin UI uses when it warns that a role needs a licence, so its answer is the billing answer. There is no published list of WEM-triggering permissions to work from, and nothing here is scraped.",
      "The result is checked against the licences each user actually holds, because the two mismatches cost money in opposite directions: a permission granted that the org is not paying for, and a WEM seat no role ever needed. Both are filterable, as Unlicensed trigger and License unused.",
      "The page works out which licence counts as WEM and tells you what it is checking, rather than opening with every licence your organisation holds and asking you to choose one. There is nothing to pick: this page answers who holds a WEM licence and how they got it, and picking a licence would mean knowing which of your SKUs is the WEM one.",
      "Everything exports to Excel, with the full list of triggering permissions per row rather than the abbreviated one the table has room for.",
      "Group memberships are read once, with the bulk user fetch, rather than one request per user found. On an org where WEM is widely deployed that is the difference between a few dozen requests and a few thousand — the number of requests now follows the number of roles and groups, not the size of the directory.",
      "An organisation on Genesys Cloud CX 3 or above has no WEM add-on to select, because CX 3 already includes WEM. The page now says so — and says that nobody in such an organisation can be carrying a WEM permission it is not paying for — rather than asking you to pick a licence that does not exist for you.",
    ],
  },
  {
    version: "4.6",
    date: "2026-08-25",
    title: "Data Actions: a page shaped like the job",
    changes: [
      "Data Actions › Edit no longer has its own organisation dropdown. It uses the one in the header, like every other single-org page in the app.",
      "The action picker is a searchable dropdown instead of a scrolling list box with a separate search field beside it. Category, integration and status remain as filters, but sit out of the way until there are actions to filter.",
      "Contract, Configuration and Test are now three collapsible sections in the order Genesys uses, and the page opens with all three closed. Test used to be at the very bottom, behind everything else; it is now one click from the top. Contract used to be permanently expanded despite being the one thing you cannot edit.",
      "Save Draft, Validate and Publish moved to a bar directly under the picker, with the status message beside them, so they stay in view instead of scrolling away behind a long request template.",
      "Unsaved changes are now visible while you have them, rather than only being mentioned when you press Publish.",
      "A test result is shown against the action’s own output contract — each output by name, type and value — with the execution steps listed separately and the raw response kept but tucked away. Previously the whole thing was a wall of JSON, and a failing test gave you no indication of which step failed.",
      "Execution Timeout is editable, 1 to 60 seconds as Genesys allows. It was previously invisible here, so setting one meant going to Genesys.",
      "Category is no longer presented as editable. Genesys fixes it when an action is created and offers no way to change it; this page offered a text box that suggested otherwise. It is now shown as a read-only value, and the Contract section says why a published action’s contract cannot be changed instead of just showing a table you cannot edit.",
      "The status of an action — published, draft, or both — now reads as a badge rather than the first of five rows of small text, since it decides what the buttons will do.",
    ],
  },
  {
    version: "4.5",
    date: "2026-08-25",
    title: "Data Actions: the templates it showed were not the ones Genesys held",
    changes: [
      "A data action’s request and success templates are often stored by Genesys as separate files rather than as text on the action, and the app was only ever reading the text. For those actions the template boxes on the Edit page were blank — and saving a draft wrote that blank back, replacing the real template with the Genesys default. The templates are now fetched and shown wherever an action is read, on Edit, on Copy between Orgs, and in Deployment › Onboarding. If one cannot be read, the page says so and refuses to save rather than saving an empty one.",
      "Onboarding was copying those same actions into customer orgs with the default template instead of the real one, and reporting the copy as successful. It now fails the object with the reason, in the preview as well as the deploy, where it is cheapest to act on.",
      "Onboarding also treated every data action as changed. The comparison included file references that contain the action’s own ID and so can never match between two orgs, which meant an identical action was never offered for reuse and re-running a job created duplicates instead of picking its own objects back up.",
      "Invalid JSON in the Headers, Translation Map or contract boxes no longer wipes the stored value. A single stray comma was silently treated as an empty object, saved over the real one, and reported as “Draft saved”. The offending box is now marked, the save is refused, and the field is named.",
      "Saving a draft no longer clears the action’s timeout. The timeout is not editable here, but it is part of the configuration Genesys replaces wholesale on save, so leaving it out removed it.",
      "Validation failures now say what is wrong. The page was reading a field the Genesys validation endpoint does not return, so every failure rendered as “Validation issues:” with nothing after it — on the one screen whose entire purpose is telling you what to fix.",
      "A test that fails is reported as a failure. A data action that runs and errors still returns a successful HTTP response, and the page read that as the action having worked — showing a green tick above the failure it had just printed.",
      "Copy between Orgs no longer carries the source org’s file references into the destination, and no longer keeps the previous destination’s integration list when you change the destination org. Picking a second destination after loading used to leave the first one’s integrations on screen, so the copy was sent with an integration ID that org has never heard of.",
      "Editing a draft-only action keeps the parts of its contract the page has no editor for, instead of dropping them on save.",
      "Publishing with unsaved changes on screen now asks first. Publish promotes the saved draft, so edits you had typed but not saved were quietly left behind — and the page still reported “Action published”. It now offers to save them first, and does nothing if you decline.",
    ],
  },
  {
    version: "4.4",
    date: "2026-08-24",
    title: "Direct Routing: the settings it showed were not the ones Genesys held",
    changes: [
      "Backup Settings never worked, and could quietly undo itself. The page was built against a shape the API does not have, so every agent with a backup configured showed “None” — and because the form read back as a deliberate “no backup”, pressing Apply for any other reason cleared it. Backups now load, display and save correctly.",
      "An agent can have a backup user and a backup queue at the same time, which Genesys has always supported and the page could not express: the user takes the interaction first, the queue catches what is left. Each is set and cleared independently.",
      "The wait setting is no longer inverted. “Wait for Agent” beside a seconds box read as though ticking it started the wait; it is now “Send to backup immediately”, matching the wording on the Genesys queue screen, and the seconds box greys out when it does not apply. Its range was 0–600 and is now 60–864000, which is what Genesys accepts — the old minimum was rejected outright and the old maximum excluded most of the valid range.",
      "Tagging a number for direct routing no longer strips other integration tags off the user’s remaining numbers. A user with a Teams number and a work number lost the Teams tag the moment anything on their card was applied, on a row nobody had touched, in a table that did not show integrations at all. The table now has an Integration column, and the page only ever writes the value it owns.",
      "A phone number can only be tagged if it is in a Genesys DID pool, and an email only if its domain is configured for inbound email. Neither routes anything otherwise — the tag simply sits there looking correct. Numbers and addresses that cannot be used say why, and offer no control rather than a control that does nothing.",
      "New Call Routing column. A tagged number that no call route points at still routes nothing, so the column shows which route a number is on and lets it be set from a searchable list of every call route in the org. Assigning several agents to the same route in one pass writes to that route once, rather than once per agent.",
      "Users the page can do nothing for are no longer listed. Someone with no phone number and no email on a routable domain used to get a full card with every control dead.",
      "The Primary column is now read-only. It offered to set the primary phone and never did — Genesys derives it from the addresses and does not accept it being written — and Genesys advises against using the primary phone for direct routing in any case. It still shows which number is primary, which is worth knowing when choosing one to tag.",
      "Direct routing is switched on and off with a toggle instead of a radio button, so each row can be cleared on its own and the “None” row under every group is gone.",
      "Users can be narrowed by group before picking them, the way WebRTC Phones already works. Selecting people and then applying a filter no longer quietly unticks the ones outside it — they stay selected and are marked as outside the current filter.",
      "The Addresses section opens with the card rather than closed, so a card can be read without two clicks. The bulk “Auto-tag phone type for all” now reports what it did — “Work Phone 2 selected for 14 of 17 users; 3 have no Work Phone 2” — where before it flipped controls inside closed sections and appeared to do nothing at all.",
      "Cancel works during Load Details. It was hidden for the entire load, so a large selection could not be stopped.",
      "Where a Genesys permission is missing, the affected section is greyed out and names the permission — and is now genuinely unreachable rather than merely mouse-proof. Reading backup settings, removing a backup, and editing call routes are each gated separately, because Genesys grants them separately.",
    ],
  },
  {
    version: "4.3",
    date: "2026-08-23",
    title: "Move: it tells you what it will do before it does it",
    changes: [
      "Move Interactions now shows a preview you can trust, and cannot act on anything you have not seen. The button stays greyed until a preview has run \u2014 it used to search and transfer in one press, so an entire queue could be moved without ever appearing on screen, on an action that cannot be undone.",
      "Changing anything after a preview clears it. Preview one queue, notice you picked the wrong source, correct it and press Move, and the interactions from the first queue were transferred \u2014 while the confirmation named the second. Every control now discards the preview: both queues, the media types, and the dates. Cancelling a preview clears it too, rather than leaving a half-finished list armed and looking complete.",
      "The preview says where every interaction went, instead of only listing the ones it can move. \u201cNo active interactions found matching the criteria\u201d used to cover an empty queue, a media filter, a date filter, interactions with nothing left to transfer, and requests that failed \u2014 all with the same sentence. Each now has its own row and its own reason.",
      "Interactions an agent is currently handling are listed as such and left alone. That was always the behaviour; it was simply invisible, so a queue of forty could preview as thirty-two with no explanation of the other eight.",
      "The status line carries the queue\u2019s own depth beside the count: \u201c2 to move \u00b7 4 scanned \u00b7 1.204 waiting in queue \u00b7 oldest waiting 3d \u00b7 1 no active queue leg\u201d. A filter that matched nothing no longer looks like a queue that was already empty.",
      "Scanning a queue is faster. Interactions are read ten at a time instead of one, and the months that hold nothing are no longer paged through at all \u2014 a queue whose backlog is from this week no longer waits on five empty months first.",
      "The scan no longer stops at twenty thousand interactions per month. It did so silently, and because it reads newest first, what it dropped were the oldest \u2014 which on this page are usually the ones you were looking for. Above 250 interactions it now says how many it found and roughly how long reading them will take, and lets you decide. Cancel works throughout, including during the scan itself.",
      "Source and destination sit on one line with an arrow between them, and each is a single searchable dropdown rather than a search box stacked on a list. A warning at the top of the page says what a blind transfer actually does \u2014 including that a moved interaction is re-queued, so its waiting time starts again.",
      "The spinning ring that shows the app is working now appears in the same places across Disconnect, Move and both Search pages. Queue and Division dropdowns show it while they load on every one of them; previously only Move did, and the others simply greyed out \u2014 which looks identical to a dropdown that has failed to load.",
    ],
  },
  {
    version: "4.2",
    date: "2026-08-22",
    title: "Interaction Search: filters that find what you know is there",
    changes: [
      "Searching on two pieces of participant data now finds interactions that have both. Genesys routinely writes attributes onto different legs of the same conversation — one set by the flow, another by the agent — and the search insisted on finding them all on a single leg. It could not, so it found nothing, and nothing looks exactly like no such interaction exists. If you have ever been certain an interaction had both values and the search disagreed, this was why. One filter behaved correctly, which is what kept it hidden.",
      "The expanded row had been showing those same attributes side by side all along, gathered from every participant. The page was displaying a merged view and filtering against an unmerged one.",
      "An attribute stored with no value no longer breaks the whole search. One such attribute anywhere in the results turned the search into an error message rather than a result, and the interaction that carried it was not necessarily one you were looking for.",
      "Recent Search’s Participant Data filters now actually filter. They used to choose which attributes an expanded row displayed, and the Value box did nothing at all: typing UD_Language = DK gave you a filter that said so and rows with SE in them. The data is not in the search results — Genesys does not return it for the last 48 hours — so the page fetches it for each result after the search and filters on it, which is slower than Historical Search and the only route to interactions this recent.",
      "Because that costs a request per result, above 250 results it asks first, with an estimate of how long, and there is a Cancel that stops between batches. Declining or cancelling shows every result unfiltered and says so, rather than showing a partly filtered set that looks complete.",
      "Multi-value now draws the Value Distribution chart on Recent Search too. It breaks comma-separated attributes into their individual values and counts them across the results, so a rare language pair or a stray origin is visible without opening a single row. Recent Search also has the Exclude checkbox, so both search pages work the same way.",
      "Ticking Multi-value without a participant data filter no longer hides the results. There is no chart to draw without one, and the table folded away regardless, leaving a heading with nothing underneath it.",
      "Recent Search’s Conversation Detail pane shows participant data. It had listed purpose, name and disconnect type only, on a page whose whole purpose is participant data.",
      "Editing a filter after a search no longer makes the rest of the page describe a search you did not run. The value chart, the expanded rows and the participant data export all read whatever was in the form at that moment, so changing a key without pressing Search left them describing the new filter over the old results.",
      "Exported participant data from an excluded search is now named as excluded. The file held the right thing — the values carried by the interactions you kept — under a name that read months later as the ones you had searched for.",
      "Historical Search’s filters are laid out by question rather than in one long row: when, where, and what participant data. The row used to rearrange itself as the window changed width, so nothing on the page told you which controls belonged together — at some widths Exclude and Multi-value landed on separate lines. The quick ranges sit beside the dates they are shortcuts for and show which one is active, the three export buttons are one Export menu, and Search now looks like the button you came to press.",
    ],
  },
  {
    version: "4.1",
    date: "2026-08-21",
    title: "Disconnect: filter stuck emails by who sent them",
    changes: [
      "Interactions › Disconnect can now narrow a run to particular email addresses. Tick Email and two fields appear — Sender Email and Recipient Email — each taking as many addresses as you like, one per row. When a single mailbox has produced a batch of stuck interactions and the rest of the queue must be left alone, that is now a filter rather than an afternoon of copying conversation IDs out of a preview and pasting them back in.",
      "An address means email and nothing else. Whatever else is ticked under Media Types is struck through and a line says so, because a filter that quietly reinterprets the boxes above it on a page that force-disconnects things is not a filter anyone should have to guess at.",
      "Addresses match exactly, and case does not matter: support@acme.com and Support@Acme.com are the same filter, and an address pasted from a mail client as “Support <SUPPORT@Acme.com>” is read the same way. An address that is not an address stops the run and says which row it was, rather than being dropped — a dropped row would widen the very thing you were narrowing.",
      "Preview now accounts for everything it looked at. Paste ten IDs and the seven that do not qualify are listed with the reason each one was set aside, instead of the page reporting three and saying nothing about the rest. A queue scan reports the same thing as counts — “1,204 scanned · 0 match · 1,204 media type not selected” — so a filter that is too tight no longer looks like a queue that is already empty.",
      "Changing any filter after a preview now clears it. Previously the previewed set survived the change and Disconnect acted on it, so editing an address or a date and pressing the button could disconnect what the previous filter had found.",
      "Emptying a queue is quicker, and now means what it says. It asks the queue what it is holding rather than reconstructing six months of history, and skips the months that hold nothing at all — a scan that took minutes returns in seconds. It also acts on what is actually waiting: an interaction that never ended but has left the queue is no longer swept up with the rest, and is reached by its ID instead.",
      "Pasting a long list of IDs is roughly eight times faster. They were being looked up one at a time; ten now go at once. A list of three thousand was a coffee break.",
      "When you filter, the queue’s own depth sits beside the result — “4 match · 3.091 waiting in queue · oldest waiting 23h” — so a filter that matched nothing no longer looks exactly like a queue that was already empty. With no filter there is nothing to match against, so the line simply says how many are waiting.",
      "Disconnect stays greyed out until a preview has run. It used to search on its own when pressed, meaning the whole set could be disconnected without ever having been shown — on the one action in the app that cannot be undone. The confirmation also names the addresses that chose the set, and so does the Activity Log entry afterwards.",
      "Pasting the ID of an orphaned interaction works. Single and Multiple ID mode used to refuse exactly the conversations this page exists for — the ones Genesys has half-closed internally — while Empty Queue found them. Both modes now agree on what can be disconnected.",
    ],
  },
  {
    version: "4.0",
    date: "2026-08-21",
    title: "You can tell when the app is working",
    changes: [
      "Everywhere the app is waiting on something, a small spinning ring now sits beside the message that describes it. It is there for one reason: a line that has stopped changing because the work is slow and a line that has stopped changing because the work died look exactly the same. The ring is the difference. While it turns, something is still happening.",
      "The pages with a progress bar have one too. A bar tells you how much is left, which is worth knowing, but it stands perfectly still for as long as any single step takes — and a bar stuck at 40% because one request is slow looks identical to a bar stuck at 40% because the connection dropped. The bar answers how far; the ring answers whether. They are different questions.",
      "Dropdowns that fill themselves from Genesys — sites, queues, divisions, billing periods, roles — show the ring on their label while they load. Until now they said “Loading…” and then sat there, which is also what a dropdown that has failed to load says.",
      "Anywhere a panel or a table was showing the bare word “Loading”, it now shows a ring instead, so an empty page reads as one that is filling rather than one that is empty.",
      "Buttons that go away and do something — voting on a request, saving a change, deleting, sending a message — show the ring inside the button you actually pressed. The confirmation used to appear in a status line somewhere else on the page, which is not where you were looking.",
      "Opening the app, and moving between pages, no longer sits on a blank screen while it works. Pages you have already visited still appear instantly; only the ones that genuinely take a moment say so.",
    ],
  },
  {
    version: "3.9",
    date: "2026-08-20",
    title: "Requests: your vote keeps you posted",
    changes: [
      "Voting for a request now keeps you informed about it. Whenever it moves — considering, planned, being built, shipped, and equally when it is not going to happen — everyone who voted hears, not only the person who wrote it. A vote is a way of asking for something too, and one that never reports back is one nobody bothers to cast twice.",
      "That includes the outcomes nobody enjoys sending. A request that is dropped after several people voted for it is told, rather than going quiet: silence reads as having been forgotten, when what actually happened was a decision.",
      "Removing your vote stops the emails for that request, and every one of them says so. Nothing else about the request changes when you do.",
      "Filing a request now sends you a copy of it. The page already thanks you, so this is not news — it is a receipt, your own words in your own inbox, so a request is something you can find again or forward rather than something you typed into a box and hoped about.",
      "The vote control says what it does. It used to be an arrow and a number, which needed explaining; it now reads “Vote (12)”, and “Voted (13)” once you have. The wording carries the state rather than the colour alone, so it no longer depends on being able to see the difference.",
      "The three boards are named consistently — My company board, Shared board, and Triage board for those who triage. Two of them used to name a place while the third named an activity, which made one of them look like a different kind of thing.",
    ],
  },
  {
    version: "3.8",
    date: "2026-08-20",
    title: "Requests: ask for what the app is missing",
    changes: [
      "New Requests button in the header, next to Activity Log. Ask for something new, a change to something that exists, or tell us when something is not working. It needs no permission and is not part of any package — a channel for telling us what the product is missing cannot itself be something you have to be granted, so everyone signed in has it.",
      "Press it from the page you are complaining about and it remembers which one that was. A request that arrives already saying “Export › Users › Trustee”, with the organisation you had selected and the version you were running, is one we can act on instead of writing back to ask where you were. If the request is not about that page, one click clears it.",
      "Everyone in your organisation sees the same board, so a request is visible to your colleagues rather than disappearing into a mailbox. If somebody has already asked for what you were about to ask for, vote for theirs instead — the count is what tells us which of two good ideas to build first, and it is something a queue of near-identical requests can never say.",
      "We answer on the request itself, and you get an email whenever its status moves — considering, planned, being built, shipped, or not planned. A request that visibly moves is worth filing; one that vanishes is not, which is the whole reason this is a board and not a suggestion box.",
      "Each request has a discussion between you and us, for the times when what was asked for and what is actually needed are not quite the same thing. Your colleagues can read it, so nobody has to ask the same question twice, but only you and we can write in it. Both of us are emailed when the other replies.",
      "A shared board carries the requests we have published, and every organisation sees the same one. Nothing reaches it automatically: we choose what goes there and write the wording ourselves, so your own words and your organisation's name never travel to anyone else. Published requests show a first name and last initial — “Thomas V.” — and there is a box on the form to publish without your name at all.",
      "Once something you asked for ships, its request says so and links to the release note. You can see where your own words ended up.",
      "Activity Log now shows your whole organisation's activity rather than only your own. Customers already worked this way; internal staff were narrowed to their own entries, which left the people running the app as the only ones who could not see what their own organisation had done. The User column and the Org and User filters come with it, because a log of other people's actions needs them. Nothing crosses between organisations: you see your own, and never anybody else's.",
    ],
  },
  {
    version: "3.7",
    date: "2026-08-19",
    title: "Get Lists: Wrap-up Codes (internal)",
    internalOnly: true,
    changes: [
      "Utilities › Get Lists has a second list. Wrap-up Codes gives every code in the org with its name, ID, description and the division it belongs to — filtered, sorted and exported to Excel like the first one.",
      "A wrap-up code names the division it sits in, but Genesys usually returns only that division’s ID and not its name. The divisions are fetched alongside and the name filled in, so the column reads Sales rather than sitting empty. If the division list cannot be read, the codes still come through with whatever names they carried.",
    ],
  },
  {
    version: "3.6",
    date: "2026-08-19",
    title: "Export: the documentation export finishes, and a run of smaller fixes",
    changes: [
      "The documentation export finished its work but arrived too late for orgs with a large data table, and the page showed only “Server returned 500”. One table of 7,000 rows was fetched a hundred rows at a time, one request after the next, and that single chain outlasted the 45-second limit that applies to any request the app makes. Pages are now fetched several at a time — the org that was failing went from 47 seconds to 13.",
      "The second workbook holding DataTable contents was silently missing for orgs where two tables’ names matched for their first 31 characters. Excel rejects a duplicate sheet name, and the whole DataTables workbook was dropped without a word, leaving a single file where a ZIP was expected. Names are now made unique, and when the workbook genuinely cannot be built the summary says why rather than quietly handing back less.",
      "Interaction Totals read the selected org once, when the page opened. Switching org in the header afterwards left it querying the previous customer while labelling the workbook, the email and the activity log with that customer’s name. It now reads the org each time you press Load, and asks you to pick one at that point rather than showing a dead page that never recovered.",
      "Cancel stops the work. It used to set a flag that was only read once the fetching had already finished, so a large export carried on to the end after you had cancelled it.",
      "The “inactive for N months” filter on Last Login could be up to three days out at the end of a month, letting recently-active users through.",
      "Sunday was blank in the schedule sheet of the templates export, and days were written as numbers rather than names.",
      "Licence Consumption now has a column for every licence the org defines, including those nobody currently holds. Before, a licence with no holders simply vanished from the report, so “nobody uses this” and “this org does not have this” looked the same.",
      "The user counts in export summaries were counted by email address. Deleted users are included in these exports and Genesys releases their address for reuse, so users without one collapsed into a single entry and the count read lower than the table beneath it.",
      "Billing workbooks covering many orgs could fail outright when two org names matched for their first 31 characters — after every billing call for every org had already been made. Sheet names are now made unique.",
      "The trustee export no longer opens every org at once. It walked each org, then each trustee, group and member within it, which could put hundreds of simultaneous calls against a rate-limited API.",
      "Scheduled exports received the same fixes as the pages. The handlers that run them are separate ports of the same logic and carried the same faults, so the workbooks arriving by email had them too.",
    ],
  },
  {
    version: "3.5",
    date: "2026-08-18",
    title: "Utilities › Get Lists: the reference lists in an org, on screen and in Excel (internal)",
    internalOnly: true,
    changes: [
      "New page Utilities › Get Lists. Pick a list from the dropdown, click Load, and it is fetched from the selected org, shown here, and exported to Excel. Read-only — nothing is written back to Genesys. Nothing is fetched until you ask for it: opening the page calls nothing, and changing the picker only changes what Load would fetch, so adding more lists later will not mean the first one downloads itself every time the page opens. Load again to refetch.",
      "The first list is Presence Definitions. A presence definition carries a label in every language the org has translated it into, and all of them are shown — one row per language, rather than one row per definition with the translations packed into a cell. That keeps every column something you can filter and sort on, in the app and in Excel alike. Definitions that have been deactivated are included too, with their own column, so nothing is quietly left out.",
      "Every column filters, from a dropdown in the column heading itself — one header line, not a heading with a second band of filter buttons under it. Each value in the dropdown has an “only” next to it, so showing just Danish out of twenty-four languages is one click rather than unticking the other twenty-three; tick a second language to add it. There is a search box for finding a value, All and None to start from either end, and a count of how many rows of the total are showing. Clicking a column heading sorts by it, and sorting keeps whatever filters you already set rather than resetting them.",
      "Export to Excel writes what is on screen — the filters you set, in the order you sorted it — not the unfiltered list. Filter down to the four Danish labels you came for and that is the file you get.",
      "The page is built to grow. Each list is one entry in a registry naming its endpoint, its columns and how to read the response; the fetching, the table, the filters, the sorting and the export are shared. Adding the next list is that entry, not another page.",
      "Utilities › Permission Catalog: the table heading was a black band in light mode. It was painted a fixed dark colour rather than a theme one, which only showed for anyone whose system is set to light.",
    ],
  },
  {
    version: "3.4",
    date: "2026-08-18",
    title: "WebRTC Phones — Create on a schedule, and tighter API access",
    changes: [
      "Phones › WebRTC › Create now has an Automation panel, like the export pages. Pick an org, a destination site, optional group and division filters, and a time — daily, weekly or monthly — and the same job runs unattended and emails the Excel log when it finishes.",
      "A scheduled run has nobody reading the review first, so it refuses to write when its own checks look wrong. It stops before creating anything if the org has WebRTC phones but none could be matched to a user — the failure that would otherwise hand a duplicate phone to everyone — and if the run would create more phones than the safety limit you set on the schedule.",
      "A schedule cannot outlive the authority of whoever made it. Before each run the creator is looked up again, and the job is refused if they are no longer an active user or no longer hold the phone permission. Schedules created by internal staff need one setting naming which configured org is your own (INTERNAL_ORG_SLUG) — no new credentials — and until it is set those runs report that the check could not be made rather than implying it happened.",
      "Each org still only sees its own schedules, exactly as with the existing export schedules.",
      "The schedule list shows when each one last ran and how it went, as the Scheduled Exports overview does. A run that refused itself says why in that column — the reason is the useful part, so it is shown rather than a bare \"Failure\".",
      "Security: several backend endpoints were reachable without signing in. The customer list, the on-demand Documentation export and the email sender now all require a signed-in caller, and a customer session is held to its own org. Scheduled exports could also be pointed at a different org than the one that created them; the target org is now locked the same way the templates already were.",
    ],
  },
  {
    version: "3.3",
    date: "2026-08-17",
    title: "Deployment › Test › Test Cases: a flow's test document, written for you (internal)",
    internalOnly: true,
    changes: [
      "New page Deployment › Test › Test Cases, marked Still Work in Progress while we gather opinions on it. Pick a flow, choose how thoroughly to cover it, and every route a caller can take through it comes out as a test case: what has to be true to send the call down that route, the steps it goes through, and where it ends up. Read-only — nothing is written to Genesys.",
      "Three levels of coverage, because a flow with twenty decisions in it has a million routes through it and nobody tests a million things. Branch coverage is the default and gives you every branch exercised at least once — on that same twenty-decision flow, two test cases cover all forty branches. Happy paths gives one case per distinct ending. All paths gives you everything, capped at 500 per flow, and says so plainly when it stops early rather than handing you a document that quietly stops short.",
      "Cases come out ordered with the ones that matter first: highest priority is a route that reaches an agent without going through an error handler, lowest is one that goes through a failure, timeout or no-input path, or that ends without resolving at all.",
      "Everything the flow depends on is covered too — common modules, in-queue flows and bot flows are found automatically and each gets its own set of cases. A step that calls a common module names it and points at that module's own cases, rather than pretending one test case can span two flows: Architect does not record which of a module's endings maps to which of the caller's outputs, so that link would be invented.",
      "Conditions are stated, not guessed. Where a route depends on a value, the document tells you the condition that has to hold — Flow.CustomerType == \"Gold\" — and leaves setting it up to you, instead of inventing a value that might not satisfy it.",
      "Branches nothing can reach are reported rather than skipped, and told apart from branches you could only reach by going round a loop a second time. The first usually means something in the flow is wired to nothing, or a task nothing jumps to — worth knowing about, and easy to miss reading a flow by eye; one production bot flow has 180 of them. The second is simply a limit of testing each route once. Queues, prompts and schedules the flow picks at run time by expression cannot be listed by name at all, so they get their own sheet to check by hand.",
      "Where a switch is involved, the document spells out the whole condition rather than saying \"Case 3\", which nobody knows by heart — and because a switch takes the first case that matches, it also states which earlier cases must NOT match. Setting up data that satisfies case 3 while case 1 also matches would send the call somewhere else entirely and fail the test for the wrong reason. A decision says which way its condition has to go, rather than just naming it next to Yes or No.",
      "Checked against 18 real exported flows covering every flow type, from 4 nodes to 854. Branch coverage reaches 100% on nine of them and 98–99% on three more; the largest flow produces 162 test cases in well under a second.",
      "Export writes a styled Excel workbook, customer name first: a summary, one row per test case with empty Result, Tester, Date and Notes columns to fill in as you go, the numbered steps in the shape a test tool imports, a coverage sheet showing which case covers which branch, and the manual checks. The summary also states what the document does not claim, so someone handed just the file knows where its limits are.",
      "Under the hood, Flow Overview and Test Cases now share one flow loader rather than each keeping a copy, so a fix to how dependencies are discovered reaches both.",
    ],
  },
  {
    version: "3.2",
    date: "2026-08-17",
    title: "Flows › Flow Overview: every flow type, and a dependency export",
    changes: [
      "Messaging, email and bot flows are drawn properly. A flow groups its top level differently by type — states for messaging and email, bots for bot flows, tasks everywhere — and only tasks were being read, so everything else was skipped along with all of its contents. One messaging flow was losing 47 of its 130 actions, and the start marker sat on the wrong box. Change State is drawn to the state it moves to, and Exit Bot Flow ends its path instead of running on.",
      "Ask for Intent is drawn as the branch point it is — one labelled connection per intent, going wherever that intent routes — instead of a dead-end Collect Input that hid all fifteen branches behind it. A bot's Anything Else loop is drawn as a loop with its body nested inside, and handlers that are switched off, such as an unused Max No Inputs, no longer appear as paths the flow can take.",
      "Call Task and Jump to Task are now told apart: Call Task returns to the next action, Jump to Task hands control over for good, and both are drawn to the task they target with its real name. Jump to Menu is drawn to its target menu, and a Call Task shows the output paths of the task it calls (Failure, Timeout, …) alongside its normal return.",
      "A flow's menus get their own box, with every DTMF choice drawn as a labelled branch into the actions behind it — sub-menus nest inside their parent, a choice that jumps straight to a task is drawn as that jump, and Repeat Menu loops back to the menu it belongs to. Menus were previously left out of the diagram altogether.",
      "The start of a flow is findable: a START marker that stays the same size however far you zoom out, clamped to the edge and clickable when the start is off screen, a Start button in the toolbar, and the start box itself drawn solid and thick with a START tag that carries into the PDF and HTML exports.",
      "A switch lists every case in full, in first-true order, and each case's condition rides on its connection — hover the line or click it. Call Bot Flow and Call Digital Bot Flow register the bot flow they call as a dependency, so it appears in the diagram, the search panel, the dependency export and its own tab.",
      "Skills, screen pop scripts, flow outcomes and milestones count as dependencies too, alongside data tables, data actions, common modules, bot flows, queues, prompts, schedule groups and wrap-up codes. Milestones and flow outcomes are left off the Mid and Low diagrams — one flow declares 66 of them, which would bury the tasks those levels exist to show — but they are listed in full in the search panel, the details panel and the dependency export.",
      "Export Dependencies writes a styled Excel workbook covering the root flow and every dependency flow, named after the customer first: one sheet listing each dependency with its type, name and — for data actions — the integration category it comes from; one listing every individual use, traced to its task and action; and one listing the queues, prompts and schedules the flow resolves at run time by expression, which cannot be listed by name and need checking by hand when moving a flow between orgs.",
      "A flow type filter sits beside the flow picker, offering only the types the org actually has and narrowing the list alongside the name search.",
    ],
  },
  {
    version: "3.1",
    date: "2026-08-14",
    title: "Divisions: move Skills and Wrap-up Codes between divisions",
    changes: [
      "Genesys made ACD skills division aware, and wrap-up codes already were. Both now have their own page under Divisions › Routing, working the same way as every other page in the section: load, narrow by source division or search by name, tick what to move, pick a target division, apply.",
      "Wrap-up codes could already be given a division one at a time from Wrapup Codes › Create/Edit/Mapping. The new page is for moving many at once, and shows the division each code sits in today — including the ones still on All.",
      "On that same Create/Edit page, choosing \"(No division)\" for an existing code now states the change rather than leaving the field out of the save, so the result no longer depends on what Genesys does with a missing value.",
    ],
  },
  {
    version: "3.0",
    date: "2026-08-14",
    title: "Data Tables › Edit: the key column fits its keys",
    changes: [
      "Rows mode sizes the key column to the widest key in the table instead of giving it the same fixed width as every other column. Tables with short keys stop spending screen space on an empty column, and the space goes to the columns you are editing.",
      "The width is measured across every row, not just the page on screen, so the column stays put as you page through the table.",
    ],
  },
  {
    version: "2.9",
    date: "2026-08-13",
    title: "Phones: find and delete WebRTC phones nobody is using",
    changes: [
      "New page Phones › WebRTC › Delete. Analyse lists the WebRTC phones nobody is using — no user assigned, or a user who has been deleted or deactivated — grouped by reason. Nothing is deleted until you review the list and confirm.",
      "Phones with no user, or a deleted user, are ticked ready to go. Phones belonging to an inactive user are listed unticked, so removing one is a deliberate choice.",
      "Phones Genesys will not return when asked for them individually are listed in their own section and cannot be selected. Not knowing who holds a phone is not the same as knowing nobody does.",
      "Only phones on a WebRTC base are considered, so shared desk and conference phones are never listed. An optional Site filter narrows the sweep further.",
      "Confirming requires typing DELETE, and every phone is re-checked immediately before it goes — anything assigned to an active user since you ran the report is kept and reported instead. There is no undo, though a phone can be recreated from Create.",
      "The Findings panel states what the run actually saw: how many phones were examined, and how many users were read in each state. An empty category is only meaningful if the lookup behind it returned anything, so it says when one did not.",
      "Every run writes an Activity Log entry, and the Excel log covers every phone considered, including the ones kept and why.",
    ],
  },
  {
    version: "2.8",
    date: "2026-08-13",
    title: "WebRTC Phones — Change Site: filters, and a confirmation before moving",
    changes: [
      "Optional Groups and Division filters, matching the phone's holder: \"show me the phones belonging to people in Sales\". Leave them empty to list everything at the site. A phone with no assigned user cannot match either filter and drops out when one is set, with the count stated.",
      "Moving now asks for confirmation, restating how many phones and where they are going. Moving a phone re-registers it and can drop anyone on a call through it, so the run no longer starts on a single click.",
      "The destination can no longer be the source. Previously choosing the same site on both sides ran a move that changed nothing and still reported every phone as moved.",
      "Failures include the status code, and rate-limit responses are retried instead of being recorded as failures.",
      "After a run the phone list clears — it described phones that are no longer at the source site. A run that breaks part-way still writes its Activity Log entry for the phones already moved.",
    ],
  },
  {
    version: "2.7",
    date: "2026-08-13",
    title: "WebRTC Phones — Create: see who gets a phone before any are made",
    changes: [
      "Phones › WebRTC › Create now works in two steps. Analyse reads the org's active users, their licences and its existing phones, and shows exactly who would get a phone and who would be skipped, with the reason. Nothing is created until you confirm.",
      "A user is skipped for one of three reasons: they already have a WebRTC phone, they hold only a collaborate licence, or they hold no licence at all. Only active users are considered.",
      "The collaborate rule now actually applies. It never fired in earlier versions — licences were read in the wrong shape, so collaborate users were sent to Genesys anyway. A user holding a collaborate licence alongside a real one correctly still gets a phone.",
      "Users who already have a phone are found up front rather than by a create that fails, so no request is sent for anyone already set up. The phone list does not always name a phone's user, so the ones it cannot account for are read individually.",
      "Optional Groups and Division filters narrow who a run covers, and combine: a group plus a division gives the people in both. The summary states both numbers — \"40 of 900 active users (group 'Sales Team')\" — so a narrow run never reads like an org-wide one.",
      "Phone names that would clash with an existing phone are adjusted automatically and flagged in the review. Before, the second person with the same name simply failed.",
      "Failures say what went wrong. Previously any error whose text happened to contain '400' or '409' was recorded as 'already exists', which hid real problems.",
      "The Findings panel lists the licences found in the org and which were read as collaborate, and how many existing phones were matched to users.",
      "Rows can be unticked, the confirmation restates the count and destination site, rate-limit responses are retried, and the Excel log covers everyone considered — skipped users with their reason, unticked or unreached users as 'Not run'.",
    ],
  },
  {
    version: "2.6",
    date: "2026-08-13",
    title: "Flows: delete a callflow and everything only it used (internal)",
    internalOnly: true,
    changes: [
      "New page Flows › Delete Flow — the opposite of Deployment › Onboarding. Pick one callflow and it works out everything that callflow depends on, checks what else in the org still uses each of those objects, and shows you the whole picture before anything is removed.",
      "Objects nothing else uses are ticked ready to go: other flows, common modules, data tables, data actions, scripts, survey forms and prompts. Objects something else still needs are listed too, with the name of what is holding them, so you know what to detach if you want them gone.",
      "The ticks are live. A data table used only by a common module can be removed only while that module is also being removed — untick the module and the table locks itself again, along with anything else that depended on it.",
      "Queues, skills, schedules and similar org-level objects are always listed but never ticked for you. They can be referenced in ways that are impossible to see from the callflow, so removing one is always a deliberate choice.",
      "If the callflow itself cannot be deleted — attached to a web or messaging deployment, a call route, a queue's in-queue flow, or simply open in Architect — you are told exactly what is holding it and nothing below it can be removed either, since the flow still uses all of it.",
      "Deletion happens in dependency order and every object is re-checked immediately before it is removed, so anything that has gained a user since you ran the report is kept and reported rather than deleted.",
      "Confirming requires typing the callflow's name. Data tables show how many rows will go with them. There is no undo.",
      "Every run writes one Activity Log entry with the full breakdown — what was deleted, and what was kept and why.",
      "Rows show who created each object where Genesys records it, including when the object was created by an integration rather than a person.",
      "Two things this cannot see, by design: anything referenced only while a call is running (a queue looked up by name, a prompt named in a data table cell), and the contents of data tables — those are never scanned. Published survey forms also cannot be deleted; Genesys does not allow it, and the report says so.",
      "Available to Master Admins and superusers. Not available to the ordinary Admin group, and never to customer logins.",
    ],
  },
  {
    version: "2.5",
    date: "2026-08-12",
    title: "Onboarding: prompts are deployed too (internal)",
    internalOnly: true,
    changes: [
      "Deployment › Onboarding now brings across the user prompts a callflow refers to directly. Previously they were missed entirely, which left the deployed flow pointing at a prompt that does not exist in the destination org.",
      "A new Prompts step appears in the deploy results, before Flows, listing each prompt and how many languages were copied.",
      "The prompt, its description and every language’s text-to-speech wording and tags are copied. The recorded audio is not — customers record their own, so a copied prompt carries the wording but no sound file.",
      "Where a source prompt has only a recording and no wording, the prompt’s own name is used as placeholder wording. Without it the copied prompt would have nothing to play at all and the callflow would fail to publish. The results list and the Activity Log both flag which languages got a placeholder, so you can see what still needs recording.",
      "The placeholder clears itself: once someone records audio for that prompt, the recording takes precedence over the wording and the placeholder is never heard again.",
      "Prompt names are copied exactly as they are: the “Template - ” removal and any name prefix you set do not apply to them, because prompt names cannot contain those characters.",
      "If a prompt of the same name already exists in the destination it is reused by default, on the assumption that it is the customer’s own recording. You can still choose to create a separate one, which is named with an underscore (for example TemplateTestPrompt_2).",
      "If a callflow refers to a prompt that is missing from the source org, that is now reported as a warning rather than passing silently.",
      "Prompts that are looked up while the call is running — where the name comes from a data table — are not covered by this. Only prompts referenced directly in the callflow are deployed.",
    ],
  },
  {
    version: "2.4",
    date: "2026-08-12",
    title: "Onboarding: see what will be deployed before it happens (internal)",
    internalOnly: true,
    changes: [
      "Deployment › Onboarding now works out everything it would create — including all the dependencies it discovers — before writing anything to the destination org.",
      "New “Preview and Deploy” button: always stops and shows you the full plan first. Nothing is created until you press Deploy now.",
      "The ordinary “Deploy” button still runs straight through, but stops if there is something to decide: a name that already exists in the destination, or a problem found that would make the deploy fail (for example a data action whose integration is missing in the destination). Previously that failure only appeared partway through, after other objects had already been created.",
      "When a name already exists you now choose per object: keep the existing one, or create a new one alongside it under a different name. You can set a suffix for all of them at once and still rename any individually.",
      "The choice is pre-selected for you by comparing the existing object with the source: identical means it is reused, while one that has been changed since it was deployed defaults to creating a new object — so an edit made by a colleague or a customer no longer silently becomes part of your deployment.",
      "Architect flows cannot be compared this way, so instead you are told when an earlier deploy of the same source and destination created the flow.",
      "You have 30 minutes to confirm; a countdown is shown. After that the preview is abandoned, nothing is deployed, and the Activity Log records it as previewed only — never as a deploy.",
      "Confirming deploys exactly what you were shown, and is faster than starting over: nothing needs to be exported from the source org a second time.",
    ],
  },
  {
    version: "2.3",
    date: "2026-08-12",
    title: "Onboarding: phases with nothing to deploy are now listed (internal)",
    internalOnly: true,
    changes: [
      "Deployment › Onboarding: when a deploy has no data tables, data actions, scripts or survey forms to create, the step is now listed in the results with e.g. “No scripts found” instead of being left out.",
      "Previously the Scripts and Survey forms steps disappeared entirely in that case, and Data tables / Data actions showed an empty section — so you couldn’t tell “nothing was referenced” apart from “this step didn’t run”.",
      "The step indicator at the top shows these steps normally rather than greyed out.",
      "These informational lines are not counted as created, skipped or failed, so the deploy totals are unchanged.",
      "The same lines appear under Details on the deploy’s Activity Log entry.",
    ],
  },
  {
    version: "2.2",
    date: "2026-08-12",
    title: "Onboarding deploys in the Activity Log (internal)",
    internalOnly: true,
    changes: [
      "Deployment › Onboarding now records every deploy in the Activity Log — one entry per job, attributed to the operator who started it, against the target org.",
      "Because an onboarding deploy runs in the background long after you click Deploy, the entry is written when the job finishes — including when it fails outright — so the record no longer depends on keeping the page open.",
      "Click Details on the entry to expand the full breakdown: source and target org, division, name prefix, the callflows you picked, and every created / skipped / failed object per phase, plus any warnings.",
      "The result badge reflects the job: success, partial (some objects failed) or failure. Failed object names are shown on the row itself, so you can spot a problem without expanding it.",
      "Very large deploys are summarised to fit the log entry — failures are always kept, and the entry says when the item list was shortened.",
      "The Action filter gained the missing Deployment — Onboarding, Deployment — Basic and Data Table Create entries.",
    ],
  },
  {
    version: "2.1",
    date: "2026-08-11",
    title: "Sign-in: pop-out authentication",
    changes: [
      "Login now uses a pop-out sign-in window instead of loading the Genesys login page inside the embedded app. This prepares the app for the Genesys Cloud deprecation of iframe-embedded login (effective 4 February 2027).",
      "When your session is needed, the app shows a “Sign in with Genesys” button. Clicking it opens a small sign-in window; if you are already signed in to Genesys Cloud, it recognises your session and closes automatically — no credentials to re-enter.",
      "If your browser blocks the sign-in window, allow pop-ups for the app and click Sign in again.",
    ],
  },
  {
    version: "2.0",
    date: "2026-08-08",
    title: "Flows › Flow Overview",
    changes: [
      "New Flows › Flow Overview: an interactive, read-only graphical overview of an Architect callflow and all of its dependency flows. Pick an org and a live flow and the whole call flow is drawn as a diagram.",
      "Built from the flow's structured Archy/SDK YAML (exported on demand), so implicit ‘Default’ paths that the flat REST config leaves out are drawn correctly.",
      "Tasks and loops are shown as nested boxes (loops inside their task, inner loops inside outer loops), and every task starts at its true first action. Decisions, switches, menus, data-table lookups, data actions, common-module calls, transfers and jumps all get labelled connections.",
      "A tab per dependency flow — common modules, in-queue flows, transfer/bot targets of any type (including outbound) — discovered automatically from referenced flow names.",
      "High / Mid / Low detail levels, dark/light/white themes, fullscreen, and a combined variable & dependency search: click a variable to jump to where it is set or used, or a dependency to open its flow.",
      "Click any node to see the values set in that node, its condition/expression, referenced flow or called task, and variables used; click a connection to see its From/To.",
      "Download as PDF, self-contained HTML, or JSON — either the current flow, or Save all, which auto-loads every dependency flow (including nested common modules) and bundles them into one file: a multi-page PDF, a single tabbed HTML file, or one combined JSON.",
    ],
  },
  {
    version: "1.9",
    date: "2026-08-06",
    title: "Data Tables › Edit improvements",
    changes: [
      "Rows mode: wide tables are no longer cramped — column headers stay readable and the grid scrolls horizontally with a comfortable minimum column width.",
      "Rows mode: the horizontal scrollbar now sits above the rows for easier access.",
      "Rows mode: new Copy Row button (between Add Row and Delete Selected). Enabled only when exactly one row is selected; it asks for the new key value and adds a pending copy that you save with Save Changes.",
      "The data table selector is now a searchable dropdown — type to filter tables by name.",
    ],
  },
  {
    version: "1.8",
    date: "2026-08-02",
    title: "Deployment › Onboarding (internal)",
    internalOnly: true,
    changes: [
      "New Deployment › Onboarding: one-click deploy a curated template set from a source (demo) org into a customer org under a chosen division. Source defaults to the Demo org (unlock other sources with the “Other orgs” checkbox).",
      "Pick callflows; all dependencies — common modules, in-queue flows, transfer/post-flow targets, data tables, data actions, screen-pop scripts and survey forms — are auto-discovered and deployed in the right order, with every internal reference (GUID) rewritten for the target org.",
      "Screen-pop scripts are published so flows can reference them; voice-survey flows are recreated from their (deployed & published) survey forms.",
      "Optional name prefix: created objects can be named “prefix - Original name”. Create a target division inline. Filter callflows by name and by type.",
      "Live phase-by-phase progress stepper plus the detailed per-item results (created / skipped / error).",
      "Outbound call flows are intentionally not supported (they require a contact list, which has no template equivalent) and are excluded from the picker.",
    ],
  },
  {
    version: "1.7",
    date: "2026-07-17",
    title: "Data Tables copy: edit columns before saving",
    changes: [
      "Data Tables > Copy (Single Org) and Copy between Orgs now let you add or remove schema columns before the copy is saved. Selecting a source table shows an editable column list (Name / Type / Default) with drag-to-reorder, matching the Create/Edit editor.",
      "When 'Copy data' is enabled, copied rows are filtered to the columns kept in the edited schema: removed columns are dropped and added columns take their default value.",
      "The primary key column is always preserved from the source and cannot be removed.",
    ],
  },
  {
    version: "1.6",
    date: "2026-07-17",
    title: "Customer-facing foundation, data-store isolation & security notices",
    changes: [
      "Customer-facing capability (foundation): the app can now serve external customers against their OWN Genesys org with strict tenant isolation and purchased-module (package) access. Customers log into their own region and are locked to their org; the selectable module set comes from their entitlements. Internal/staff usage is unchanged.",
      "Data-store isolation: app-owned stores are now org-aware. Templates and template assignments are cross-org for staff but locked to a customer's own org for customers. Activity Log, Scheduled Exports, and Template Schedules are owner-scoped — each org only sees records its own session created (customers never see internal data, and staff never see customer-created records).",
      "Note for staff: saving templates/schedules and viewing the Activity Log now rely on your active login session — if you get an unexpected error there, refresh the page to renew your session.",
      "Internal-only features (Utilities, Deployment, cross-org copies, Trustee/All-Orgs/Billing exports) are explicitly unavailable in customer mode.",
      "Security: added a self-XSS console warning on load (don't paste code someone sends you into the browser console) and a proprietary/copyright notice (© 2026 TDC Erhverv) in the sidebar footer.",
    ],
  },
  {
    version: "1.5",
    date: "2026-07-08",
    title: "Fix: Data Tables schema edit no longer drops columns",
    changes: [
      "Fixed a bug in Data Tables > Edit (Schema mode) where saving could fail with \"Field '…' is missing from the proposed schema\" and, in some cases, drop an existing column.",
      "The editor now preserves each column's original schema property key across the load/save round-trip, instead of re-keying properties by their display title.",
      "Column titles can still be edited freely; new columns continue to key by their name. Adding a column no longer surfaces the pre-existing key/title mismatch.",
    ],
  },
  {
    version: "1.4",
    date: "2026-07-07",
    title: "Step 4: server-side proxy tenant enforcement",
    changes: [
      "The Genesys proxy now decides mode from the caller's own token (verified server-side via organizations/me, cached), never from the request body.",
      "The elevated client-credentials path now requires a verified internal-org token, closing the previous unauthenticated access path to /api/genesys-proxy.",
      "Customer sessions are token-forwarded and locked to their own org/region; any attempt to target another org via the request body is rejected (403 org_locked).",
      "Added a customer-mode denylist for internal/trustee/billing endpoints, plus an optional positive entitlement allowlist (ENFORCE_ENTITLEMENT_ALLOWLIST, default off).",
      "Internal/demo behavior is unchanged; deployments without org env configured keep the legacy behavior via a compatibility fallback.",
    ],
  },
  {
    version: "1.3",
    date: "2026-07-07",
    title: "Step 3 foundation: server-owned org context",
    changes: [
      "Added `GET /api/org-config` to resolve auth mode server-side from the signed-in user's org (`/api/v2/organizations/me`) and return safe org context.",
      "Added org-hint support (`?org=`) through the PKCE login flow so customer deep links can be validated after authentication.",
      "App startup now uses `/api/org-config` before rendering org selection: customer mode locks to one org; internal mode keeps the existing selector behavior.",
      "Introduced compatibility fallback for existing internal deployments where `INTERNAL_COMPANY_ORG_ID` and `CUSTOMER_REGISTRY_JSON` are not configured yet.",
    ],
  },
  {
    version: "1.2",
    date: "2026-07-06",
    title: "Permission-aware access for write actions",
    changes: [
      "Write features are now gated by your own Genesys permissions in addition to app group membership: you can only perform an action (create, edit, delete, apply) if your Genesys role includes the matching permission.",
      "Read-only features (Export, Audit, Flows, Roles Compare/Search, Interaction Search) are unaffected and remain governed by group access alone.",
      "Features you can't use appear disabled in the sidebar with a tooltip naming the required permission; opening one directly shows which permission is missing.",
      "Within a page, individual actions and sections you lack the permission for are disabled too — e.g. Delete rows, Publish/Test a data action, backup routing, and per-category template application (roles/skills/languages/queues).",
      "Create/Edit Template now requires the same permissions as Manage Templates.",
      "Full-access administrators and superusers are unaffected.",
    ],
  },
  {
    version: "1.1",
    date: "2026-07-06",
    title: "Permission Catalog page (internal)",
    internalOnly: true,
    changes: [
      "Added Utilities > Permission Catalog — an internal, admin-only page that lists the full Genesys Cloud permission catalog (domain:entity:action) for the selected org.",
      "Live filter over the permission string and label, sortable columns, and summary counts of domains, entities, and permissions.",
      "Copy permissions (all filtered strings, one per line) with an iframe-safe clipboard fallback, plus Export to Excel.",
      "Read-only; built to author and verify the feature → permission map for the upcoming customer-facing expansion.",
    ],
  },
  {
    version: "1.0",
    date: "2026-07-04",
    title: "Azure migration & Dev/Prod environments",
    changes: [
      "Migrated the app to the company Azure subscription — new Static Web App, Key Vault, Storage account, and Timer Function App.",
      "Introduced separate Dev and Prod environments with independent Azure resources and CI/CD (the main branch deploys to Dev, the production branch deploys to Prod).",
      "The OAuth redirect now derives from the current site origin, so the same build runs unchanged on both the Dev and Prod URLs.",
      "Added this Release Notes page and a version indicator in the sidebar footer — click the version to open it.",
    ],
  },
];

/** Current app version — the newest release note. Single source of truth. */
export const APP_VERSION = RELEASE_NOTES[0].version;
