/**
 * Release notes — newest entry first.
 *
 * This file is the single source of truth for the app version. Each entry
 * carries an explicit two-number `version` (e.g. "1.0", "1.1", "2.0").
 * The newest entry's version is exported as APP_VERSION and shown in the
 * sidebar footer, so the footer and the latest release note never drift.
 *
 * To cut a release: add a new object at the TOP with the next version
 * number and that release's changes.
 */
export const RELEASE_NOTES = [
  {
    version: "3.7",
    date: "2026-08-19",
    title: "Get Lists: Wrap-up Codes (internal)",
    internalOnly: true,
    changes: [
      "Utilities › Get Lists has a second list. Wrap-up Codes gives every code in the org with its name, ID, description and the division it belongs to — filtered, sorted and exported to Excel like the first one.",
      "A wrap-up code names the division it sits in, but Genesys usually returns only that division’s ID and not its name. The divisions are fetched alongside and the name filled in, so the column reads Sales rather than sitting empty. If the division list cannot be read, the codes still come through with whatever names they carried.",
    ],
  },
  {
    version: "3.6",
    date: "2026-08-19",
    title: "Export: the documentation export finishes, and a run of smaller fixes",
    changes: [
      "The documentation export finished its work but arrived too late for orgs with a large data table, and the page showed only “Server returned 500”. One table of 7,000 rows was fetched a hundred rows at a time, one request after the next, and that single chain outlasted the 45-second limit that applies to any request the app makes. Pages are now fetched several at a time — the org that was failing went from 47 seconds to 13.",
      "The second workbook holding DataTable contents was silently missing for orgs where two tables’ names matched for their first 31 characters. Excel rejects a duplicate sheet name, and the whole DataTables workbook was dropped without a word, leaving a single file where a ZIP was expected. Names are now made unique, and when the workbook genuinely cannot be built the summary says why rather than quietly handing back less.",
      "Interaction Totals read the selected org once, when the page opened. Switching org in the header afterwards left it querying the previous customer while labelling the workbook, the email and the activity log with that customer’s name. It now reads the org each time you press Load, and asks you to pick one at that point rather than showing a dead page that never recovered.",
      "Cancel stops the work. It used to set a flag that was only read once the fetching had already finished, so a large export carried on to the end after you had cancelled it.",
      "The “inactive for N months” filter on Last Login could be up to three days out at the end of a month, letting recently-active users through.",
      "Sunday was blank in the schedule sheet of the templates export, and days were written as numbers rather than names.",
      "Licence Consumption now has a column for every licence the org defines, including those nobody currently holds. Before, a licence with no holders simply vanished from the report, so “nobody uses this” and “this org does not have this” looked the same.",
      "The user counts in export summaries were counted by email address. Deleted users are included in these exports and Genesys releases their address for reuse, so users without one collapsed into a single entry and the count read lower than the table beneath it.",
      "Billing workbooks covering many orgs could fail outright when two org names matched for their first 31 characters — after every billing call for every org had already been made. Sheet names are now made unique.",
      "The trustee export no longer opens every org at once. It walked each org, then each trustee, group and member within it, which could put hundreds of simultaneous calls against a rate-limited API.",
      "Scheduled exports received the same fixes as the pages. The handlers that run them are separate ports of the same logic and carried the same faults, so the workbooks arriving by email had them too.",
    ],
  },
  {
    version: "3.5",
    date: "2026-08-18",
    title: "Utilities › Get Lists: the reference lists in an org, on screen and in Excel (internal)",
    internalOnly: true,
    changes: [
      "New page Utilities › Get Lists. Pick a list from the dropdown, click Load, and it is fetched from the selected org, shown here, and exported to Excel. Read-only — nothing is written back to Genesys. Nothing is fetched until you ask for it: opening the page calls nothing, and changing the picker only changes what Load would fetch, so adding more lists later will not mean the first one downloads itself every time the page opens. Load again to refetch.",
      "The first list is Presence Definitions. A presence definition carries a label in every language the org has translated it into, and all of them are shown — one row per language, rather than one row per definition with the translations packed into a cell. That keeps every column something you can filter and sort on, in the app and in Excel alike. Definitions that have been deactivated are included too, with their own column, so nothing is quietly left out.",
      "Every column filters, from a dropdown in the column heading itself — one header line, not a heading with a second band of filter buttons under it. Each value in the dropdown has an “only” next to it, so showing just Danish out of twenty-four languages is one click rather than unticking the other twenty-three; tick a second language to add it. There is a search box for finding a value, All and None to start from either end, and a count of how many rows of the total are showing. Clicking a column heading sorts by it, and sorting keeps whatever filters you already set rather than resetting them.",
      "Export to Excel writes what is on screen — the filters you set, in the order you sorted it — not the unfiltered list. Filter down to the four Danish labels you came for and that is the file you get.",
      "The page is built to grow. Each list is one entry in a registry naming its endpoint, its columns and how to read the response; the fetching, the table, the filters, the sorting and the export are shared. Adding the next list is that entry, not another page.",
      "Utilities › Permission Catalog: the table heading was a black band in light mode. It was painted a fixed dark colour rather than a theme one, which only showed for anyone whose system is set to light.",
    ],
  },
  {
    version: "3.4",
    date: "2026-08-18",
    title: "WebRTC Phones — Create on a schedule, and tighter API access",
    changes: [
      "Phones › WebRTC › Create now has an Automation panel, like the export pages. Pick an org, a destination site, optional group and division filters, and a time — daily, weekly or monthly — and the same job runs unattended and emails the Excel log when it finishes.",
      "A scheduled run has nobody reading the review first, so it refuses to write when its own checks look wrong. It stops before creating anything if the org has WebRTC phones but none could be matched to a user — the failure that would otherwise hand a duplicate phone to everyone — and if the run would create more phones than the safety limit you set on the schedule.",
      "A schedule cannot outlive the authority of whoever made it. Before each run the creator is looked up again, and the job is refused if they are no longer an active user or no longer hold the phone permission. Schedules created by internal staff need one setting naming which configured org is your own (INTERNAL_ORG_SLUG) — no new credentials — and until it is set those runs report that the check could not be made rather than implying it happened.",
      "Each org still only sees its own schedules, exactly as with the existing export schedules.",
      "The schedule list shows when each one last ran and how it went, as the Scheduled Exports overview does. A run that refused itself says why in that column — the reason is the useful part, so it is shown rather than a bare \"Failure\".",
      "Security: several backend endpoints were reachable without signing in. The customer list, the on-demand Documentation export and the email sender now all require a signed-in caller, and a customer session is held to its own org. Scheduled exports could also be pointed at a different org than the one that created them; the target org is now locked the same way the templates already were.",
    ],
  },
  {
    version: "3.3",
    date: "2026-08-17",
    title: "Deployment › Test › Test Cases: a flow's test document, written for you",
    changes: [
      "New page Deployment › Test › Test Cases, marked Still Work in Progress while we gather opinions on it. Pick a flow, choose how thoroughly to cover it, and every route a caller can take through it comes out as a test case: what has to be true to send the call down that route, the steps it goes through, and where it ends up. Read-only — nothing is written to Genesys.",
      "Three levels of coverage, because a flow with twenty decisions in it has a million routes through it and nobody tests a million things. Branch coverage is the default and gives you every branch exercised at least once — on that same twenty-decision flow, two test cases cover all forty branches. Happy paths gives one case per distinct ending. All paths gives you everything, capped at 500 per flow, and says so plainly when it stops early rather than handing you a document that quietly stops short.",
      "Cases come out ordered with the ones that matter first: highest priority is a route that reaches an agent without going through an error handler, lowest is one that goes through a failure, timeout or no-input path, or that ends without resolving at all.",
      "Everything the flow depends on is covered too — common modules, in-queue flows and bot flows are found automatically and each gets its own set of cases. A step that calls a common module names it and points at that module's own cases, rather than pretending one test case can span two flows: Architect does not record which of a module's endings maps to which of the caller's outputs, so that link would be invented.",
      "Conditions are stated, not guessed. Where a route depends on a value, the document tells you the condition that has to hold — Flow.CustomerType == \"Gold\" — and leaves setting it up to you, instead of inventing a value that might not satisfy it.",
      "Branches nothing can reach are reported rather than skipped, and told apart from branches you could only reach by going round a loop a second time. The first usually means something in the flow is wired to nothing, or a task nothing jumps to — worth knowing about, and easy to miss reading a flow by eye; one production bot flow has 180 of them. The second is simply a limit of testing each route once. Queues, prompts and schedules the flow picks at run time by expression cannot be listed by name at all, so they get their own sheet to check by hand.",
      "Where a switch is involved, the document spells out the whole condition rather than saying \"Case 3\", which nobody knows by heart — and because a switch takes the first case that matches, it also states which earlier cases must NOT match. Setting up data that satisfies case 3 while case 1 also matches would send the call somewhere else entirely and fail the test for the wrong reason. A decision says which way its condition has to go, rather than just naming it next to Yes or No.",
      "Checked against 18 real exported flows covering every flow type, from 4 nodes to 854. Branch coverage reaches 100% on nine of them and 98–99% on three more; the largest flow produces 162 test cases in well under a second.",
      "Export writes a styled Excel workbook, customer name first: a summary, one row per test case with empty Result, Tester, Date and Notes columns to fill in as you go, the numbered steps in the shape a test tool imports, a coverage sheet showing which case covers which branch, and the manual checks. The summary also states what the document does not claim, so someone handed just the file knows where its limits are.",
      "Under the hood, Flow Overview and Test Cases now share one flow loader rather than each keeping a copy, so a fix to how dependencies are discovered reaches both.",
    ],
  },
  {
    version: "3.2",
    date: "2026-08-17",
    title: "Flows › Flow Overview: every flow type, and a dependency export",
    changes: [
      "Messaging, email and bot flows are drawn properly. A flow groups its top level differently by type — states for messaging and email, bots for bot flows, tasks everywhere — and only tasks were being read, so everything else was skipped along with all of its contents. One messaging flow was losing 47 of its 130 actions, and the start marker sat on the wrong box. Change State is drawn to the state it moves to, and Exit Bot Flow ends its path instead of running on.",
      "Ask for Intent is drawn as the branch point it is — one labelled connection per intent, going wherever that intent routes — instead of a dead-end Collect Input that hid all fifteen branches behind it. A bot's Anything Else loop is drawn as a loop with its body nested inside, and handlers that are switched off, such as an unused Max No Inputs, no longer appear as paths the flow can take.",
      "Call Task and Jump to Task are now told apart: Call Task returns to the next action, Jump to Task hands control over for good, and both are drawn to the task they target with its real name. Jump to Menu is drawn to its target menu, and a Call Task shows the output paths of the task it calls (Failure, Timeout, …) alongside its normal return.",
      "A flow's menus get their own box, with every DTMF choice drawn as a labelled branch into the actions behind it — sub-menus nest inside their parent, a choice that jumps straight to a task is drawn as that jump, and Repeat Menu loops back to the menu it belongs to. Menus were previously left out of the diagram altogether.",
      "The start of a flow is findable: a START marker that stays the same size however far you zoom out, clamped to the edge and clickable when the start is off screen, a Start button in the toolbar, and the start box itself drawn solid and thick with a START tag that carries into the PDF and HTML exports.",
      "A switch lists every case in full, in first-true order, and each case's condition rides on its connection — hover the line or click it. Call Bot Flow and Call Digital Bot Flow register the bot flow they call as a dependency, so it appears in the diagram, the search panel, the dependency export and its own tab.",
      "Skills, screen pop scripts, flow outcomes and milestones count as dependencies too, alongside data tables, data actions, common modules, bot flows, queues, prompts, schedule groups and wrap-up codes. Milestones and flow outcomes are left off the Mid and Low diagrams — one flow declares 66 of them, which would bury the tasks those levels exist to show — but they are listed in full in the search panel, the details panel and the dependency export.",
      "Export Dependencies writes a styled Excel workbook covering the root flow and every dependency flow, named after the customer first: one sheet listing each dependency with its type, name and — for data actions — the integration category it comes from; one listing every individual use, traced to its task and action; and one listing the queues, prompts and schedules the flow resolves at run time by expression, which cannot be listed by name and need checking by hand when moving a flow between orgs.",
      "A flow type filter sits beside the flow picker, offering only the types the org actually has and narrowing the list alongside the name search.",
    ],
  },
  {
    version: "3.1",
    date: "2026-08-14",
    title: "Divisions: move Skills and Wrap-up Codes between divisions",
    changes: [
      "Genesys made ACD skills division aware, and wrap-up codes already were. Both now have their own page under Divisions › Routing, working the same way as every other page in the section: load, narrow by source division or search by name, tick what to move, pick a target division, apply.",
      "Wrap-up codes could already be given a division one at a time from Wrapup Codes › Create/Edit/Mapping. The new page is for moving many at once, and shows the division each code sits in today — including the ones still on All.",
      "On that same Create/Edit page, choosing \"(No division)\" for an existing code now states the change rather than leaving the field out of the save, so the result no longer depends on what Genesys does with a missing value.",
    ],
  },
  {
    version: "3.0",
    date: "2026-08-14",
    title: "Data Tables › Edit: the key column fits its keys",
    changes: [
      "Rows mode sizes the key column to the widest key in the table instead of giving it the same fixed width as every other column. Tables with short keys stop spending screen space on an empty column, and the space goes to the columns you are editing.",
      "The width is measured across every row, not just the page on screen, so the column stays put as you page through the table.",
    ],
  },
  {
    version: "2.9",
    date: "2026-08-13",
    title: "Phones: find and delete WebRTC phones nobody is using",
    changes: [
      "New page Phones › WebRTC › Delete. Analyse lists the WebRTC phones nobody is using — no user assigned, or a user who has been deleted or deactivated — grouped by reason. Nothing is deleted until you review the list and confirm.",
      "Phones with no user, or a deleted user, are ticked ready to go. Phones belonging to an inactive user are listed unticked, so removing one is a deliberate choice.",
      "Phones Genesys will not return when asked for them individually are listed in their own section and cannot be selected. Not knowing who holds a phone is not the same as knowing nobody does.",
      "Only phones on a WebRTC base are considered, so shared desk and conference phones are never listed. An optional Site filter narrows the sweep further.",
      "Confirming requires typing DELETE, and every phone is re-checked immediately before it goes — anything assigned to an active user since you ran the report is kept and reported instead. There is no undo, though a phone can be recreated from Create.",
      "The Findings panel states what the run actually saw: how many phones were examined, and how many users were read in each state. An empty category is only meaningful if the lookup behind it returned anything, so it says when one did not.",
      "Every run writes an Activity Log entry, and the Excel log covers every phone considered, including the ones kept and why.",
    ],
  },
  {
    version: "2.8",
    date: "2026-08-13",
    title: "WebRTC Phones — Change Site: filters, and a confirmation before moving",
    changes: [
      "Optional Groups and Division filters, matching the phone's holder: \"show me the phones belonging to people in Sales\". Leave them empty to list everything at the site. A phone with no assigned user cannot match either filter and drops out when one is set, with the count stated.",
      "Moving now asks for confirmation, restating how many phones and where they are going. Moving a phone re-registers it and can drop anyone on a call through it, so the run no longer starts on a single click.",
      "The destination can no longer be the source. Previously choosing the same site on both sides ran a move that changed nothing and still reported every phone as moved.",
      "Failures include the status code, and rate-limit responses are retried instead of being recorded as failures.",
      "After a run the phone list clears — it described phones that are no longer at the source site. A run that breaks part-way still writes its Activity Log entry for the phones already moved.",
    ],
  },
  {
    version: "2.7",
    date: "2026-08-13",
    title: "WebRTC Phones — Create: see who gets a phone before any are made",
    changes: [
      "Phones › WebRTC › Create now works in two steps. Analyse reads the org's active users, their licences and its existing phones, and shows exactly who would get a phone and who would be skipped, with the reason. Nothing is created until you confirm.",
      "A user is skipped for one of three reasons: they already have a WebRTC phone, they hold only a collaborate licence, or they hold no licence at all. Only active users are considered.",
      "The collaborate rule now actually applies. It never fired in earlier versions — licences were read in the wrong shape, so collaborate users were sent to Genesys anyway. A user holding a collaborate licence alongside a real one correctly still gets a phone.",
      "Users who already have a phone are found up front rather than by a create that fails, so no request is sent for anyone already set up. The phone list does not always name a phone's user, so the ones it cannot account for are read individually.",
      "Optional Groups and Division filters narrow who a run covers, and combine: a group plus a division gives the people in both. The summary states both numbers — \"40 of 900 active users (group 'Sales Team')\" — so a narrow run never reads like an org-wide one.",
      "Phone names that would clash with an existing phone are adjusted automatically and flagged in the review. Before, the second person with the same name simply failed.",
      "Failures say what went wrong. Previously any error whose text happened to contain '400' or '409' was recorded as 'already exists', which hid real problems.",
      "The Findings panel lists the licences found in the org and which were read as collaborate, and how many existing phones were matched to users.",
      "Rows can be unticked, the confirmation restates the count and destination site, rate-limit responses are retried, and the Excel log covers everyone considered — skipped users with their reason, unticked or unreached users as 'Not run'.",
    ],
  },
  {
    version: "2.6",
    date: "2026-08-13",
    title: "Flows: delete a callflow and everything only it used (internal)",
    internalOnly: true,
    changes: [
      "New page Flows › Delete Flow — the opposite of Deployment › Onboarding. Pick one callflow and it works out everything that callflow depends on, checks what else in the org still uses each of those objects, and shows you the whole picture before anything is removed.",
      "Objects nothing else uses are ticked ready to go: other flows, common modules, data tables, data actions, scripts, survey forms and prompts. Objects something else still needs are listed too, with the name of what is holding them, so you know what to detach if you want them gone.",
      "The ticks are live. A data table used only by a common module can be removed only while that module is also being removed — untick the module and the table locks itself again, along with anything else that depended on it.",
      "Queues, skills, schedules and similar org-level objects are always listed but never ticked for you. They can be referenced in ways that are impossible to see from the callflow, so removing one is always a deliberate choice.",
      "If the callflow itself cannot be deleted — attached to a web or messaging deployment, a call route, a queue's in-queue flow, or simply open in Architect — you are told exactly what is holding it and nothing below it can be removed either, since the flow still uses all of it.",
      "Deletion happens in dependency order and every object is re-checked immediately before it is removed, so anything that has gained a user since you ran the report is kept and reported rather than deleted.",
      "Confirming requires typing the callflow's name. Data tables show how many rows will go with them. There is no undo.",
      "Every run writes one Activity Log entry with the full breakdown — what was deleted, and what was kept and why.",
      "Rows show who created each object where Genesys records it, including when the object was created by an integration rather than a person.",
      "Two things this cannot see, by design: anything referenced only while a call is running (a queue looked up by name, a prompt named in a data table cell), and the contents of data tables — those are never scanned. Published survey forms also cannot be deleted; Genesys does not allow it, and the report says so.",
      "Available to Master Admins and superusers. Not available to the ordinary Admin group, and never to customer logins.",
    ],
  },
  {
    version: "2.5",
    date: "2026-08-12",
    title: "Onboarding: prompts are deployed too (internal)",
    internalOnly: true,
    changes: [
      "Deployment › Onboarding now brings across the user prompts a callflow refers to directly. Previously they were missed entirely, which left the deployed flow pointing at a prompt that does not exist in the destination org.",
      "A new Prompts step appears in the deploy results, before Flows, listing each prompt and how many languages were copied.",
      "The prompt, its description and every language’s text-to-speech wording and tags are copied. The recorded audio is not — customers record their own, so a copied prompt carries the wording but no sound file.",
      "Where a source prompt has only a recording and no wording, the prompt’s own name is used as placeholder wording. Without it the copied prompt would have nothing to play at all and the callflow would fail to publish. The results list and the Activity Log both flag which languages got a placeholder, so you can see what still needs recording.",
      "The placeholder clears itself: once someone records audio for that prompt, the recording takes precedence over the wording and the placeholder is never heard again.",
      "Prompt names are copied exactly as they are: the “Template - ” removal and any name prefix you set do not apply to them, because prompt names cannot contain those characters.",
      "If a prompt of the same name already exists in the destination it is reused by default, on the assumption that it is the customer’s own recording. You can still choose to create a separate one, which is named with an underscore (for example TemplateTestPrompt_2).",
      "If a callflow refers to a prompt that is missing from the source org, that is now reported as a warning rather than passing silently.",
      "Prompts that are looked up while the call is running — where the name comes from a data table — are not covered by this. Only prompts referenced directly in the callflow are deployed.",
    ],
  },
  {
    version: "2.4",
    date: "2026-08-12",
    title: "Onboarding: see what will be deployed before it happens (internal)",
    internalOnly: true,
    changes: [
      "Deployment › Onboarding now works out everything it would create — including all the dependencies it discovers — before writing anything to the destination org.",
      "New “Preview and Deploy” button: always stops and shows you the full plan first. Nothing is created until you press Deploy now.",
      "The ordinary “Deploy” button still runs straight through, but stops if there is something to decide: a name that already exists in the destination, or a problem found that would make the deploy fail (for example a data action whose integration is missing in the destination). Previously that failure only appeared partway through, after other objects had already been created.",
      "When a name already exists you now choose per object: keep the existing one, or create a new one alongside it under a different name. You can set a suffix for all of them at once and still rename any individually.",
      "The choice is pre-selected for you by comparing the existing object with the source: identical means it is reused, while one that has been changed since it was deployed defaults to creating a new object — so an edit made by a colleague or a customer no longer silently becomes part of your deployment.",
      "Architect flows cannot be compared this way, so instead you are told when an earlier deploy of the same source and destination created the flow.",
      "You have 30 minutes to confirm; a countdown is shown. After that the preview is abandoned, nothing is deployed, and the Activity Log records it as previewed only — never as a deploy.",
      "Confirming deploys exactly what you were shown, and is faster than starting over: nothing needs to be exported from the source org a second time.",
    ],
  },
  {
    version: "2.3",
    date: "2026-08-12",
    title: "Onboarding: phases with nothing to deploy are now listed (internal)",
    internalOnly: true,
    changes: [
      "Deployment › Onboarding: when a deploy has no data tables, data actions, scripts or survey forms to create, the step is now listed in the results with e.g. “No scripts found” instead of being left out.",
      "Previously the Scripts and Survey forms steps disappeared entirely in that case, and Data tables / Data actions showed an empty section — so you couldn’t tell “nothing was referenced” apart from “this step didn’t run”.",
      "The step indicator at the top shows these steps normally rather than greyed out.",
      "These informational lines are not counted as created, skipped or failed, so the deploy totals are unchanged.",
      "The same lines appear under Details on the deploy’s Activity Log entry.",
    ],
  },
  {
    version: "2.2",
    date: "2026-08-12",
    title: "Onboarding deploys in the Activity Log (internal)",
    internalOnly: true,
    changes: [
      "Deployment › Onboarding now records every deploy in the Activity Log — one entry per job, attributed to the operator who started it, against the target org.",
      "Because an onboarding deploy runs in the background long after you click Deploy, the entry is written when the job finishes — including when it fails outright — so the record no longer depends on keeping the page open.",
      "Click Details on the entry to expand the full breakdown: source and target org, division, name prefix, the callflows you picked, and every created / skipped / failed object per phase, plus any warnings.",
      "The result badge reflects the job: success, partial (some objects failed) or failure. Failed object names are shown on the row itself, so you can spot a problem without expanding it.",
      "Very large deploys are summarised to fit the log entry — failures are always kept, and the entry says when the item list was shortened.",
      "The Action filter gained the missing Deployment — Onboarding, Deployment — Basic and Data Table Create entries.",
    ],
  },
  {
    version: "2.1",
    date: "2026-08-11",
    title: "Sign-in: pop-out authentication",
    changes: [
      "Login now uses a pop-out sign-in window instead of loading the Genesys login page inside the embedded app. This prepares the app for the Genesys Cloud deprecation of iframe-embedded login (effective 4 February 2027).",
      "When your session is needed, the app shows a “Sign in with Genesys” button. Clicking it opens a small sign-in window; if you are already signed in to Genesys Cloud, it recognises your session and closes automatically — no credentials to re-enter.",
      "If your browser blocks the sign-in window, allow pop-ups for the app and click Sign in again.",
    ],
  },
  {
    version: "2.0",
    date: "2026-08-08",
    title: "Flows › Flow Overview",
    changes: [
      "New Flows › Flow Overview: an interactive, read-only graphical overview of an Architect callflow and all of its dependency flows. Pick an org and a live flow and the whole call flow is drawn as a diagram.",
      "Built from the flow's structured Archy/SDK YAML (exported on demand), so implicit ‘Default’ paths that the flat REST config leaves out are drawn correctly.",
      "Tasks and loops are shown as nested boxes (loops inside their task, inner loops inside outer loops), and every task starts at its true first action. Decisions, switches, menus, data-table lookups, data actions, common-module calls, transfers and jumps all get labelled connections.",
      "A tab per dependency flow — common modules, in-queue flows, transfer/bot targets of any type (including outbound) — discovered automatically from referenced flow names.",
      "High / Mid / Low detail levels, dark/light/white themes, fullscreen, and a combined variable & dependency search: click a variable to jump to where it is set or used, or a dependency to open its flow.",
      "Click any node to see the values set in that node, its condition/expression, referenced flow or called task, and variables used; click a connection to see its From/To.",
      "Download as PDF, self-contained HTML, or JSON — either the current flow, or Save all, which auto-loads every dependency flow (including nested common modules) and bundles them into one file: a multi-page PDF, a single tabbed HTML file, or one combined JSON.",
    ],
  },
  {
    version: "1.9",
    date: "2026-08-06",
    title: "Data Tables › Edit improvements",
    changes: [
      "Rows mode: wide tables are no longer cramped — column headers stay readable and the grid scrolls horizontally with a comfortable minimum column width.",
      "Rows mode: the horizontal scrollbar now sits above the rows for easier access.",
      "Rows mode: new Copy Row button (between Add Row and Delete Selected). Enabled only when exactly one row is selected; it asks for the new key value and adds a pending copy that you save with Save Changes.",
      "The data table selector is now a searchable dropdown — type to filter tables by name.",
    ],
  },
  {
    version: "1.8",
    date: "2026-08-02",
    title: "Deployment › Onboarding (internal)",
    internalOnly: true,
    changes: [
      "New Deployment › Onboarding: one-click deploy a curated template set from a source (demo) org into a customer org under a chosen division. Source defaults to the Demo org (unlock other sources with the “Other orgs” checkbox).",
      "Pick callflows; all dependencies — common modules, in-queue flows, transfer/post-flow targets, data tables, data actions, screen-pop scripts and survey forms — are auto-discovered and deployed in the right order, with every internal reference (GUID) rewritten for the target org.",
      "Screen-pop scripts are published so flows can reference them; voice-survey flows are recreated from their (deployed & published) survey forms.",
      "Optional name prefix: created objects can be named “prefix - Original name”. Create a target division inline. Filter callflows by name and by type.",
      "Live phase-by-phase progress stepper plus the detailed per-item results (created / skipped / error).",
      "Outbound call flows are intentionally not supported (they require a contact list, which has no template equivalent) and are excluded from the picker.",
    ],
  },
  {
    version: "1.7",
    date: "2026-07-17",
    title: "Data Tables copy: edit columns before saving",
    changes: [
      "Data Tables > Copy (Single Org) and Copy between Orgs now let you add or remove schema columns before the copy is saved. Selecting a source table shows an editable column list (Name / Type / Default) with drag-to-reorder, matching the Create/Edit editor.",
      "When 'Copy data' is enabled, copied rows are filtered to the columns kept in the edited schema: removed columns are dropped and added columns take their default value.",
      "The primary key column is always preserved from the source and cannot be removed.",
    ],
  },
  {
    version: "1.6",
    date: "2026-07-17",
    title: "Customer-facing foundation, data-store isolation & security notices",
    changes: [
      "Customer-facing capability (foundation): the app can now serve external customers against their OWN Genesys org with strict tenant isolation and purchased-module (package) access. Customers log into their own region and are locked to their org; the selectable module set comes from their entitlements. Internal/staff usage is unchanged.",
      "Data-store isolation: app-owned stores are now org-aware. Templates and template assignments are cross-org for staff but locked to a customer's own org for customers. Activity Log, Scheduled Exports, and Template Schedules are owner-scoped — each org only sees records its own session created (customers never see internal data, and staff never see customer-created records).",
      "Note for staff: saving templates/schedules and viewing the Activity Log now rely on your active login session — if you get an unexpected error there, refresh the page to renew your session.",
      "Internal-only features (Utilities, Deployment, cross-org copies, Trustee/All-Orgs/Billing exports) are explicitly unavailable in customer mode.",
      "Security: added a self-XSS console warning on load (don't paste code someone sends you into the browser console) and a proprietary/copyright notice (© 2026 TDC Erhverv) in the sidebar footer.",
    ],
  },
  {
    version: "1.5",
    date: "2026-07-08",
    title: "Fix: Data Tables schema edit no longer drops columns",
    changes: [
      "Fixed a bug in Data Tables > Edit (Schema mode) where saving could fail with \"Field '…' is missing from the proposed schema\" and, in some cases, drop an existing column.",
      "The editor now preserves each column's original schema property key across the load/save round-trip, instead of re-keying properties by their display title.",
      "Column titles can still be edited freely; new columns continue to key by their name. Adding a column no longer surfaces the pre-existing key/title mismatch.",
    ],
  },
  {
    version: "1.4",
    date: "2026-07-07",
    title: "Step 4: server-side proxy tenant enforcement",
    changes: [
      "The Genesys proxy now decides mode from the caller's own token (verified server-side via organizations/me, cached), never from the request body.",
      "The elevated client-credentials path now requires a verified internal-org token, closing the previous unauthenticated access path to /api/genesys-proxy.",
      "Customer sessions are token-forwarded and locked to their own org/region; any attempt to target another org via the request body is rejected (403 org_locked).",
      "Added a customer-mode denylist for internal/trustee/billing endpoints, plus an optional positive entitlement allowlist (ENFORCE_ENTITLEMENT_ALLOWLIST, default off).",
      "Internal/demo behavior is unchanged; deployments without org env configured keep the legacy behavior via a compatibility fallback.",
    ],
  },
  {
    version: "1.3",
    date: "2026-07-07",
    title: "Step 3 foundation: server-owned org context",
    changes: [
      "Added `GET /api/org-config` to resolve auth mode server-side from the signed-in user's org (`/api/v2/organizations/me`) and return safe org context.",
      "Added org-hint support (`?org=`) through the PKCE login flow so customer deep links can be validated after authentication.",
      "App startup now uses `/api/org-config` before rendering org selection: customer mode locks to one org; internal mode keeps the existing selector behavior.",
      "Introduced compatibility fallback for existing internal deployments where `INTERNAL_COMPANY_ORG_ID` and `CUSTOMER_REGISTRY_JSON` are not configured yet.",
    ],
  },
  {
    version: "1.2",
    date: "2026-07-06",
    title: "Permission-aware access for write actions",
    changes: [
      "Write features are now gated by your own Genesys permissions in addition to app group membership: you can only perform an action (create, edit, delete, apply) if your Genesys role includes the matching permission.",
      "Read-only features (Export, Audit, Flows, Roles Compare/Search, Interaction Search) are unaffected and remain governed by group access alone.",
      "Features you can't use appear disabled in the sidebar with a tooltip naming the required permission; opening one directly shows which permission is missing.",
      "Within a page, individual actions and sections you lack the permission for are disabled too — e.g. Delete rows, Publish/Test a data action, backup routing, and per-category template application (roles/skills/languages/queues).",
      "Create/Edit Template now requires the same permissions as Manage Templates.",
      "Full-access administrators and superusers are unaffected.",
    ],
  },
  {
    version: "1.1",
    date: "2026-07-06",
    title: "Permission Catalog page",
    changes: [
      "Added Utilities > Permission Catalog — an internal, admin-only page that lists the full Genesys Cloud permission catalog (domain:entity:action) for the selected org.",
      "Live filter over the permission string and label, sortable columns, and summary counts of domains, entities, and permissions.",
      "Copy permissions (all filtered strings, one per line) with an iframe-safe clipboard fallback, plus Export to Excel.",
      "Read-only; built to author and verify the feature → permission map for the upcoming customer-facing expansion.",
    ],
  },
  {
    version: "1.0",
    date: "2026-07-04",
    title: "Azure migration & Dev/Prod environments",
    changes: [
      "Migrated the app to the company Azure subscription — new Static Web App, Key Vault, Storage account, and Timer Function App.",
      "Introduced separate Dev and Prod environments with independent Azure resources and CI/CD (the main branch deploys to Dev, the production branch deploys to Prod).",
      "The OAuth redirect now derives from the current site origin, so the same build runs unchanged on both the Dev and Prod URLs.",
      "Added this Release Notes page and a version indicator in the sidebar footer — click the version to open it.",
    ],
  },
];

/** Current app version — the newest release note. Single source of truth. */
export const APP_VERSION = RELEASE_NOTES[0].version;
