/**
 * The pages a Supervisor scope may hold — the server's copy of the nav.
 *
 * Generated by scripts/build-pages.mjs from js/navConfig.js and checked in,
 * because the API cannot read the client's modules at runtime. Every entry
 * is a page an internal colleague may hold; `customer: true` marks the ones
 * a customer may hold as well (docs/customer-roles-design.md §6,
 * docs/internal-roles-design.md §6).
 */
const { pages } = require("./pages.json");
const INTERNAL = new Set(pages.map((p) => p.key));
const CUSTOMER = new Set(pages.filter((p) => p.customer).map((p) => p.key));

/** @param {"internal"|"customer"} kind */
function keysFor(kind) {
  return kind === "internal" ? INTERNAL : CUSTOMER;
}

/**
 * Keep the keys an org of this kind may hold; name the rest.
 * @param {unknown} list   whatever the request sent
 * @param {"internal"|"customer"} kind
 * @returns {{ kept: string[], dropped: string[] }}  kept is sorted and unique
 */
function filterPages(list, kind) {
  const valid = keysFor(kind);
  const kept = new Set(), dropped = [];
  for (const raw of Array.isArray(list) ? list : []) {
    const key = String(raw || "").trim();
    if (!key) continue;
    if (valid.has(key)) kept.add(key); else dropped.push(key);
  }
  return { kept: [...kept].sort(), dropped };
}

module.exports = { filterPages, keysFor, pages };
